.TH YED-LANG-FORTRAN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/c \- Filetype for Fortran.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "Fortran".
Matches file extensions .f, .F, .for, .ftn, .f90, .f95, and .f03.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, fortran
